import assert from 'node:assert/strict';
import { derive, aggregate, reportRevenue } from '../public/shared/metrics.js';
import { decisionBrief, evidencePack, answerQuestion, saveDecision } from '../public/shared/decisions.js';

assert.equal(derive({ cost: 100, revenue: 200, recurringRevenue: 50 }).roas, 2.5);
assert.equal(reportRevenue({ totalRevenue: 0, revenue: 200 }), 0);
assert.equal(aggregate([{ revenue: 100, recurringRevenue: 50 }, { totalRevenue: 20, revenue: 5 }]).totalRevenue, 170);
const row = { id: 'secret-campaign', name: 'Private name', cost: 100, revenue: 20, sales: 10 };
const snapshot = { generatedAt: '2026-09-23T10:00:00Z', account: { currency: 'USD' }, ranges: { '7d': { start: '2026-09-17', end: '2026-09-23', levels: { campaign: [row] }, totals: row } }, health: { scripts: { 'https://private.example': 'SCRIPT_NOT_FOUND' } } };
snapshot.generatedAt = new Date().toISOString();
const brief = decisionBrief(snapshot);
assert(brief.issues.some(x => x.id === 'efficiency:secret-campaign'));
assert(!JSON.stringify(evidencePack(brief)).includes('Private name'));
assert(!JSON.stringify(evidencePack(brief)).includes('private.example'));
assert(!JSON.stringify(evidencePack(brief)).includes('secret-campaign'));
assert(answerQuestion('revenue summary', brief).text.includes('20.00'));
assert(answerQuestion('arbitrary unsupported text', brief).text.includes('No verified answer'));
assert.equal(saveDecision('test', 'x', 'bad-status'), false);
assert(!decisionBrief({ ...snapshot, warnings: [{ range: '7d', message: 'partial' }] }).issues.some(x => x.id.startsWith('efficiency:')));
assert.equal(decisionBrief().totals, null);
assert(decisionBrief({...snapshot, generatedAt:'2020-01-01T00:00:00Z'}).stale);
assert(!decisionBrief({...snapshot, generatedAt:'2020-01-01T00:00:00Z'}).issues.some(x=>x.id.startsWith('efficiency:')));
assert(decisionBrief({...snapshot, warnings:[{level:'crm', kind:'truncated'}]}).issues.some(x=>x.id.startsWith('efficiency:')));
assert(!decisionBrief({...snapshot, account:{}}).issues.some(x=>x.id.startsWith('efficiency:')));
const previousScript = decisionBrief({...snapshot,health:{...snapshot.health, checks:{script:{stale:true}}}});
assert(previousScript.issues.find(x=>x.id.startsWith('script:')).title.includes('previous'));
assert(evidencePack(previousScript).issues.find(x=>x.view==='health').action.includes('Previous') || evidencePack(previousScript).issues.some(x=>x.action.includes('Previous')));
assert(answerQuestion('revenue', {...brief,totals:{revenue:null,cost:null,sales:null,roas:null}}).text.includes('unknown'));
console.log('Decision rules, rebills, redaction and unsupported answers passed.');
