/**
 * Regenerates data/seed.json from the DEMO generator (public/demo.js).
 *
 * The seed is what the local preview (scripts/devserver.mjs) serves as a
 * "connected account" and what scripts/selftest.mjs checks for integrity. It
 * contains NO real customer data: every row is synthetic, built with the same
 * derive/aggregate/rollup math the live pipeline uses, so the shape can never
 * drift from a real snapshot. The deployed API never reads this file — a
 * fresh deployment shows the Demo account until a HYROS key is connected.
 */
import { writeFile } from 'node:fs/promises';
import { buildDemoSnapshot } from '../public/demo.js';
import { loadFeatures, applyDemoFeatures } from '../public/shared/features.js';

const snapshot = applyDemoFeatures(buildDemoSnapshot(), await loadFeatures());
snapshot.origin = 'seed';
snapshot.seedNote = 'Synthetic preview data generated by scripts/make-seed.mjs from public/demo.js. Not customer data.';

await writeFile(new URL('../data/seed.json', import.meta.url), `${JSON.stringify(snapshot, null, 2)}\n`);

const lv = snapshot.ranges['7d'].levels;
console.log('seed written (synthetic)');
console.log('  adsets   ', lv.adset.length);
console.log('  ads      ', lv.ad.length);
console.log('  campaigns', lv.campaign.length);
console.log('  traffic  ', lv.traffic.length);
console.log('  accounts ', lv.account.length);
console.log('  leads    ', snapshot.crm.leads.length);
console.log('  7d cost  ', snapshot.ranges['7d'].totals.cost.toFixed(2));
